/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Title model module.
 * @module model/Title
 * @version 1.0.0
 */
class Title {
    /**
     * Constructs a new <code>Title</code>.
     * @alias module:model/Title
     * @param title {String} 
     */
    constructor(title) { 
        
        Title.initialize(this, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title) { 
        obj['title'] = title;
    }

    /**
     * Constructs a <code>Title</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Title} obj Optional instance to populate.
     * @return {module:model/Title} The populated <code>Title</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Title();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Title.prototype['_id'] = undefined;

/**
 * @member {String} title
 */
Title.prototype['title'] = undefined;






export default Title;

